"""Generate seller + buyer EVM wallets and write to .env file."""
from eth_account import Account

seller = Account.create()
buyer = Account.create()

env_content = f"""# x402 MVP wallets -- Base Sepolia testnet
# Generated by generate_wallets.py

# Seller (resource server) -- receives payments
SELLER_ADDRESS={seller.address}
SELLER_PRIVATE_KEY={seller.key.hex()}

# Buyer (client) -- sends payments
BUYER_ADDRESS={buyer.address}
BUYER_PRIVATE_KEY={buyer.key.hex()}

# Network config
FACILITATOR_URL=https://x402.org/facilitator
NETWORK=eip155:84532
"""

with open(".env", "w") as f:
    f.write(env_content)

print(f"Seller address: {seller.address}")
print(f"Buyer address:  {buyer.address}")
print()
print("Written to .env")
print()
print("Next step: fund the buyer wallet with testnet USDC on Base Sepolia.")
print(f"  1. Get Base Sepolia ETH from https://www.coinbase.com/faucets/base-ethereum-sepolia-faucet")
print(f"  2. Get USDC from the Base Sepolia USDC faucet or mint test USDC")
print(f"     USDC contract on Base Sepolia: 0x036CbD53842c5426634e7929541eC2318f3dCF7e")
